// pages/index/index.js
Page({
  //数据库获取数据
  shujuku(){
    wx.cloud.database().collection("users").get({
      success(res){
        console.log("数据库获取成功",res)
      },
      fail(res){
        console.log("数据库获取失败",res)
      }
    })
  },
  //云函数获取数据
  yunhanshu(){
    wx.cloud.callFunction({
      name:"getshuju",
      success(res){
        console.log("云函数获取成功",res)
      },
      fail(res){
        console.log("云函数获取失败",res)
      },
    })
  },
  getopenid(){
    wx.cloud.callFunction({
      name:"getopenid",
      data:{},
      success(res){
        console.log("获取成功",res.result.openid)
      },
      fail(res){
        console.log("获取失败",res)
      }
    })
  },
  qiuhe(){
    wx.cloud.callFunction({
      name:"add",
      data:{
        a:9,b:3
      },
      success(res){
        console.log("请求成功",res)
      },
      fail(res){
        console.log("请求失败",res)
      },
    })
  },
})